// This code Generated by  Maamri Abd Elkarim using GPT-4o 
//https://www.facebook.com/profile.php?id=100006772508580
// 22/05/2024     08:59 PM Messaad Algeria   enjoi :) 

#include <iostream>
#include <cstdlib>
#include <ctime>
#include <windows.h>
#include <vector>
#include <string>

using namespace std;

enum Choice { ROCK, PAPER, SCISSORS };

struct RoundResult {
    int roundNumber;
    string playerChoice;
    string computerChoice;
    string result;
};

Choice getComputerChoice() {
    return static_cast<Choice>(rand() % 3);
}

Choice getPlayerChoice() {
    int choice;
    cout << "Enter your choice (0 for Rock, 1 for Paper, 2 for Scissors): ";
    cin >> choice;
    return static_cast<Choice>(choice);
}

string choiceToString(Choice choice) {
    switch (choice) {
    case ROCK: return "Rock";
    case PAPER: return "Paper";
    case SCISSORS: return "Scissors";
    }
    return "";
}

void setColor(int color) {
    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE), color);
}

int main() {
    srand(static_cast<unsigned int>(time(0)));
    int playerScore = 0, computerScore = 0, rounds;
    vector<RoundResult> roundResults;

    cout << "Enter the number of rounds: ";
    cin >> rounds;

    for (int i = 0; i < rounds; ++i) {
        Choice playerChoice = getPlayerChoice();
        Choice computerChoice = getComputerChoice();
        RoundResult result;
        result.roundNumber = i + 1;
        result.playerChoice = choiceToString(playerChoice);
        result.computerChoice = choiceToString(computerChoice);

        if (playerChoice == computerChoice) {
            setColor(14); // Yellow
            cout << "Round " << (i + 1) << ": It's a tie!" << endl;
            result.result = "Tie";
        }
        else if ((playerChoice == ROCK && computerChoice == SCISSORS) ||
            (playerChoice == PAPER && computerChoice == ROCK) ||
            (playerChoice == SCISSORS && computerChoice == PAPER)) {
            setColor(10); // Green
            cout << "Round " << (i + 1) << ": Player wins!" << endl;
            ++playerScore;
            result.result = "Player wins";
        }
        else {
            setColor(12); // Red
            cout << "Round " << (i + 1) << ": Computer wins!" << endl;
            ++computerScore;
            result.result = "Computer wins";
        }

        roundResults.push_back(result);
    }

    setColor(7); // Reset to default color

    cout << "\nFinal Results:\n";
    cout << "-------------------------------------------------\n";
    cout << "| Round | Player Choice | Computer Choice | Result       |\n";
    cout << "-------------------------------------------------\n";
    for (const auto& result : roundResults) {
        cout << "| " << result.roundNumber << "     | " << result.playerChoice
            << "        | " << result.computerChoice << "         | " << result.result << " |\n";
    }
    cout << "-------------------------------------------------\n";
    cout << "| Overall Scores: Player: " << playerScore << " | Computer: " << computerScore << " |\n";
    cout << "-------------------------------------------------\n";

    if (playerScore > computerScore) {
        setColor(10); // Green
        cout << "Player is the overall winner!\n";
    }
    else if (computerScore > playerScore) {
        setColor(12); // Red
        cout << "Computer is the overall winner!\n";
    }
    else {
        setColor(14); // Yellow
        cout << "It's an overall tie!\n";
    }

    setColor(7); // Reset to default color
    return 0;
}
